import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Theme } from '../types/index';

const { width } = Dimensions.get('window');

export const getAddEntryStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme === 'light' ? '#F8FAFC' : '#1E293B',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    marginBottom: 24,
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  cameraButton: {
    backgroundColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  buttonIcon: {
    marginRight: 10,
  },
  cameraButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  previewContainer: {
    marginBottom: 24,
    backgroundColor: theme === 'light' ? 'white' : '#334155',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  image: {
    width: '100%',
    height: 300,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  inputContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme === 'light' ? '#E2E8F0' : '#475569',
  },
  inputLabel: {
    fontWeight: '700',
    color: theme === 'light' ? '#475569' : '#E2E8F0',
    fontSize: 16,
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  textInput: {
    backgroundColor: theme === 'light' ? '#F1F5F9' : '#475569',
    borderRadius: 10,
    padding: 14,
    color: theme === 'light' ? '#1E293B' : '#E2E8F0',
    fontSize: 16,
    borderWidth: 1,
    borderColor: theme === 'light' ? '#E2E8F0' : '#64748B',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  notesInput: {
    minHeight: 120,
    maxHeight: 200,
    textAlignVertical: 'top',
    lineHeight: 22,
  },
  addressContainer: {
    padding: 16,
    backgroundColor: theme === 'light' ? '#F1F5F9' : '#475569',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  addressHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  addressLabel: {
    fontWeight: '700',
    marginLeft: 8,
    color: theme === 'light' ? '#475569' : '#E2E8F0',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  addressText: {
    color: theme === 'light' ? '#1E293B' : '#E2E8F0',
    marginBottom: 14,
    fontSize: 15,
    lineHeight: 22,
  },
  coordinatesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme === 'light' ? 'rgba(13, 148, 136, 0.1)' : 'rgba(45, 212, 191, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  coordIcon: {
    marginRight: 6,
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
  },
  coordinatesText: {
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    fontSize: 12,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
  },
  noAddressText: {
    color: theme === 'light' ? '#94A3B8' : '#94A3B8',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme === 'light' ? 'rgba(255, 255, 255, 0.98)' : 'rgba(30, 41, 59, 0.98)',
    padding: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme === 'light' ? '#E2E8F0' : '#475569',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  saveButton: {
    backgroundColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    flex: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  saveButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  cancelButton: {
    backgroundColor: theme === 'light' ? '#F1F5F9' : '#475569',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme === 'light' ? '#E2E8F0' : '#64748B',
  },
  cancelButtonText: {
    color: theme === 'light' ? '#64748B' : '#E2E8F0',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    marginVertical: 28,
  },
  loadingText: {
    marginTop: 14,
    color: theme === 'light' ? '#64748B' : '#94A3B8',
    fontSize: 16,
  },
  headerBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerBackText: {
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    fontSize: 16,
    marginLeft: Platform.OS === 'ios' ? 4 : 0,
    display: Platform.OS === 'ios' ? 'flex' : 'none',
    fontWeight: '600',
  },
});