import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Theme } from '../types/index';

const { width } = Dimensions.get('window');

export const getHomeStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme === 'light' ? '#F8FAFC' : '#1E293B',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme === 'light' ? '#F8FAFC' : '#1E293B',
  },
  loadingText: {
    marginTop: 18,
    fontSize: 16,
    color: theme === 'light' ? '#64748B' : '#94A3B8',
    fontWeight: '500',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    marginTop: 24,
    letterSpacing: 0.5,
  },
  emptySubText: {
    fontSize: 16,
    color: theme === 'light' ? '#64748B' : '#94A3B8',
    marginTop: 10,
    marginBottom: 36,
    letterSpacing: 0.3,
  },
  listContent: {
    padding: 16,
    paddingTop: 20,
    paddingBottom: 90,
  },
  entryContainer: {
    position: 'relative',
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    height: 240,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  detailsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    paddingBottom: 22,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  coordinatesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  icon: {
    marginRight: 8,
    color: 'white',
  },
  address: {
    fontSize: 22,
    fontWeight: '600',
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    marginBottom: 6,
  },
  date: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  coordinates: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
  },
  addEntryButton: {
    backgroundColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    width: '75%',
    elevation: 6,
    shadowColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  addEntryButtonText: {
    color: 'white',
    fontSize: 17,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: theme === 'light' ? '#0D9488' : '#2DD4BF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  deleteButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(244, 67, 54, 0.9)',
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'black',
  },
  modalContent: {
    backgroundColor: theme === 'light' ? 'white' : '#334155',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    height: '85%',
    paddingTop: 12,
    overflow: 'hidden',
    elevation: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme === 'light' ? '#E2E8F0' : '#475569',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme === 'light' ? '#1E293B' : '#E2E8F0',
    letterSpacing: 0.3,
  },
  closeButton: {
    position: 'absolute',
    left: 16,
    padding: 8,
    backgroundColor: theme === 'light' ? 'rgba(13, 148, 136, 0.1)' : 'rgba(45, 212, 191, 0.1)',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalImage: {
    width: '100%',
    height: 280,
  },
  detailSection: {
    padding: 20,
  },
  detailTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    marginBottom: 14,
    letterSpacing: 0.5,
  },
  detailDescription: {
    fontSize: 16,
    lineHeight: 24,
    color: theme === 'light' ? '#475569' : '#94A3B8',
    marginBottom: 24,
    letterSpacing: 0.2,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  detailIcon: {
    marginRight: 14,
    marginTop: 2,
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
  },
  detailText: {
    fontSize: 16,
    color: theme === 'light' ? '#1E293B' : '#E2E8F0',
    flex: 1,
    lineHeight: 22,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 16,
  },
  tag: {
    backgroundColor: theme === 'light' ? 'rgba(13, 148, 136, 0.1)' : 'rgba(45, 212, 191, 0.1)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme === 'light' ? 'rgba(13, 148, 136, 0.3)' : 'rgba(45, 212, 191, 0.3)',
  },
  tagText: {
    color: theme === 'light' ? '#0D9488' : '#2DD4BF',
    fontSize: 14,
    fontWeight: '500',
  },
  modalFooter: {
    padding: 18,
    borderTopWidth: 1,
    borderTopColor: theme === 'light' ? '#E2E8F0' : '#475569',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme === 'light' ? 'white' : '#334155',
  },
  modalDeleteButton: {
    backgroundColor: '#F44336',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    elevation: 4,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  modalButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  buttonIcon: {
    marginRight: 8,
  },
});